# 개발
profile: dev # 사용자 환경변수
 
spring:
  profiles:
    include: core
 
  # h2 데이터베이스 설정
  h2:
    console:
      enabled: true
      path: /h2-console
 
  # DataSource 설정
  datasource:
    driver-class-name: org.h2.Driver # DB Driver (생략가능)
    url: jdbc:h2:./data/data # DB URL (ContextRoot/data/data.sql ? 에 저장)
 
 
  # JPA 설정
  jpa:
    show-sql: true # JPA 쿼리문 출력
    hibernate:
      ddl-auto: create # 서버 재시작 시 DB 테이블 삭제 후 생성 (default) - 데이터 유지 X
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # default
    properties:
      hibernate:
        format_sql: true # 쿼리문 출력 시 sql 개행처리 여부 (true 쿼리문 보기 쉬워진다)
    open-in-view: false # 기본값이 true 이기 때문에 LazyInitializationException 처리를 위해 false (https://kingbbode.tistory.com/27)
 
# Slf4j 설정
logging:
  level:
    root: info # 기본 로그는 debug 이상부터 찍힌다
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # 하이버네이트 sql 은 trace 이상부터 찍힌다
 
server:
  port: 8081
  error:
    path: /error # 서버 에러 발생 시 @GetMapping 경로
