drop table if exists HOLIDAY;


CREATE TABLE HOLIDAY (
    ID BIGINT AUTO_INCREMENT,
    DATENAME VARCHAR(50) NOT NULL,
    MONTH SMALLINT NOT NULL,
    DAY SMALLINT NOT NULL,
    ISLUNAR boolean NOT NULL,
    PRIMARY KEY (ID)
);


INSERT INTO HOLIDAY (DATENAME, MONTH, DAY, ISLUNAR) VALUES
   ('1월 1일', 1, 1, false);